### PR TITLE
🧹 Fix logic to compare compute setting to static counterparts, rather than evaluating static ComputeSetting directly

### PR DESCRIPTION
**Pull request by QuitCrypto**
The existing logic evaluates static compute setting values as conditions for ternary expressions, which will always evaluate truthy. They should instead be comparing the existing compute setting to their static counterparts.

### CODE REVIEW

**Comment by yargo13** [comment]
Nice catch, thanks! Can you generate a changeset with `pnpm changeset` ?

**Comment by yargo13** [comment]
Also saw that linter failed, fix would be
```
            const mapper =
                computeSetting === ComputeSetting.OnlyReduce
                    ? (this.logger.info('OnlyReduce setting is used. Skipping map step.'),
                      (r: RequestResponsePair) => r.response)
                    : (r: RequestResponsePair) => this.lzMap(compute, r, timeMarker)
            const reducer =
                computeSetting === ComputeSetting.OnlyMap
                    ? (this.logger.info('OnlyMap setting is used. Skipping reduce step.'),
                      (mappedResponses: string[]) => mappedResponses.join(''))
                    : (mappedResponses: string[]) => this.lzReduce(compute, cmd, mappedResponses, timeMarker)
```

**Review by yargo13 — APPROVED** [review]

**Review by yargo13 — CHANGES_REQUESTED** [review]
Let's put it as p

**Comment by QuitCrypto** [comment]
Re-marked it as a patch and rebased to sync it up with main again

**Review by yargo13 — APPROVED** [review]

**Pull request merged**
