### PR TITLE
feat(oft-solana): add hardhat task to get prio fees, --with-compute-unit-price correction and elaboration

### PR DESCRIPTION
**Pull request by nazreen**
- adds a new hardhat task that makes use of the existing `getFee` script, that can be used for program deploys when mainnet is busy, something projects are running into a lot
- correct from lamports to micro lamports
- mention `getFee` util function

You can test init a new repo by running

```
export LZ_BRANCH=nazreen/cu-price-unit-fix
LZ_ENABLE_EXPERIMENTAL_SOLANA_OFT_EXAMPLE=1 LAYERZERO_EXAMPLES_REPOSITORY_REF="#${LZ_BRANCH}" npx create-lz-oapp@latest
```

For the new hardhat task, run

`npx hardhat solana:get-prio-fees --eid <SOLANA_EID> --address <PROGRAM_ID>`

Solana Devnet EID: 40168

### CODE REVIEW

**Review by DanL0 — CHANGES_REQUESTED** [review]
looks good and seems working but please make it easier for people to call get fee by making this a hardhat task:
```
import { Connection, PublicKey } from '@solana/web3.js'
import { task } from 'hardhat/config'
import { types as devtoolsTypes } from '@layerzerolabs/devtools-evm-hardhat'
import { deriveConnection } from './index'

interface PrioritizationFeeObject {
    slot: number
    prioritizationFee: number
}

interface Config {
    lockedWritableAccounts: PublicKey[]
}

const getPrioritizationFees = async (
    connection: Connection
): Promise<{
    averageFeeIncludingZeros: number
    averageFeeExcludingZeros: number
    medianFee: number
}> => {
    try {
        const publicKey = new PublicKey('JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4')

        const config: Config = {
            lockedWritableAccounts: [publicKey],
        }

        const prioritizationFeeObjects = (await connection.getRecentPrioritizationFees(
            config
        )) as PrioritizationFeeObject[]

        if (prioritizationFeeObjects.length === 0) {
            console.log('No prioritization fee data available.')
            return { averageFeeIncludingZeros: 0, averageFeeExcludingZeros: 0, medianFee: 0 }
        }

        // Calculate the average including zero fees
        const averageFeeIncludingZeros =
            prioritizationFeeObjects.length > 0
                ? Math.floor(
                      prioritizationFeeObjects.reduce((acc, feeObject) => acc + feeObject.prioritizationFee, 0) /
                          prioritizationFeeObjects.length
                  )
                : 0

        // Filter out prioritization fees that are equal to 0 for other calculations
        const nonZeroFees = prioritizationFeeObjects
            .map((feeObject) => feeObject.prioritizationFee)
            .filter((fee) => fee !== 0)

        // Calculate the average of the non-zero fees
        const averageFeeExcludingZeros =
            nonZeroFees.length > 0 ? Math.floor(nonZeroFees.reduce((acc, fee) => acc + fee, 0) / nonZeroFees.length) : 0

        // Calculate the median of the non-zero fees
        const sortedFees = nonZeroFees.sort((a, b) => a - b)
        let medianFee = 0
        if (sortedFees.length > 0) {
            const midIndex = Math.floor(sortedFees.length / 2)
            medianFee =
                sortedFees.length % 2 !== 0
                    ? sortedFees[midIndex]
                    : Math.floor((sortedFees[midIndex - 1] + sortedFees[midIndex]) / 2)
        }
        return { averageFeeIncludingZeros, averageFeeExcludingZeros, medianFee }
    } catch (error) {
        console.error('Error fetching prioritization fees:', error)
        return { averageFeeIncludingZeros: 0, averageFeeExcludingZeros: 0, medianFee: 0 }
    }
}

task('solana:get-prioritization-fees', 'Fetches prioritization fees from the Solana network')
    .addParam('eid', 'The endpoint ID for the Solana network', undefined, devtoolsTypes.eid)
    .setAction(async ({ eid }) => {
        const { connection } = await deriveConnection(eid)
        const fees = await getPrioritizationFees(connection)
        console.log('Prioritization Fees:', fees)
    })
```

and import it in tasks/index.ts:
```
import './solana/getFee'
```

**Comment by nazreen** [comment]
PR body updated with instructions for reviewing

**Review by DanL0 — DISMISSED** [review]
we should probably change get-prio-fees to get-priority-fees but look good

**Comment by nazreen** [comment]
@DanL0 task name updated, but I kept the file name for conciseness. prio as short for priority is used by Solana's engineer who built the priority graph, so I'd say it should be acceptable for internal names

https://apfitzge.github.io/posts/solana-scheduler/

**Review by DanL0 — APPROVED** [review]

**Pull request merged**
