### PR TITLE
🪲 Add missing error to PriceFeedMock

### PR DESCRIPTION
**Pull request by 0xAkuti**
Adds missing error definition for the error `LZ_PriceFeed_NotAnOPStack` which is used in `PriceFeedMock._getL1LookupId()` and currently causing issues (https://github.com/LayerZero-Labs/devtools/issues/978).
```
Error: 
Compiler run failed:
Error (7576): Undeclared identifier.
   --> lib/devtools/packages/test-devtools-evm-foundry/contracts/mocks/PriceFeedMock.sol:184:16:
    |
184 |         revert LZ_PriceFeed_NotAnOPStack(l2Eid);
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^

```
The alternative would be to add it in `ILayerZeroPriceFeed` where the error `LZ_PriceFeed_UnknownL2Eid` which was previously used is defined, but since `LZ_PriceFeed_NotAnOPStack` seems to only be used in this mock and not in layerzero v2 adding it here seems to be the way to go.

### CODE REVIEW

**Comment by 0xAkuti** [comment]
Hi, any feedback on this? @janjakubnanista 
Would be nice to merge it since we currently use a forked repo with the fix and would like to use the official one.

**Review by janjakubnanista — CHANGES_REQUESTED** [review]
Hey @0xAkuti! Could you please include a changeset? You just need to run `pnpm changeset` from the root of the repo and mark this package as `patch`, thanks!

If you're at it I would also update the branch on top of the newest `main` from devtools, we included some bug fixes that remedied flaky test runs

**Comment by 0xAkuti** [comment]
Hi @janjakubnanista, I added the changeset and updated to the current `main`

**Comment by 0xAkuti** [comment]
It was added last week in the layerzero-v2 repo (https://github.com/LayerZero-Labs/LayerZero-v2/pull/121) in `ILayerZeroPriceFeed` like I mentioned as the alternative approach in the top comment. So it's no longer needed here.

**Comment by 0xAkuti** [comment]
Resolved with https://github.com/LayerZero-Labs/LayerZero-v2/pull/121

**Pull request closed without merging**
